<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use App\Models\User;

class TeacherSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'nip' => '197701012002111001',
                'email' => 'admin@example.com',
                'first_name' => 'Siti',
                'last_name' => 'Rahmawati',
                'degree' => 'S.Pd',
                'address' => 'Jl. Ahmad Yani No. 12',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10110',
                'country' => 'Indonesia',
                'phone_number' => '081234567890',
                'about' => 'Operator sekolah berpengalaman.',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '1977-02-02',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'operator',
                'profile' => 'profile 1.png',
            ],
            [
                'nip' => '197703032003123003',
                'email' => 'teacher1@example.com',
                'first_name' => 'Budi',
                'last_name' => 'Santoso',
                'degree' => 'M.Pd',
                'address' => 'Jl. Merdeka No. 45',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40115',
                'country' => 'Indonesia',
                'phone_number' => '081223344556',
                'about' => 'Guru Matematika.',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '1978-03-03',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 2.png',
            ],
            [
                'nip' => '197804042004124004',
                'email' => 'teacher2@example.com',
                'first_name' => 'Agus',
                'last_name' => 'Setiawan',
                'degree' => 'S.Pd',
                'address' => 'Jl. Diponegoro No. 99',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55281',
                'country' => 'Indonesia',
                'phone_number' => '081312345678',
                'about' => 'Guru Bahasa Indonesia.',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '1979-04-04',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 3.png',
            ],
            [
                'nip' => '197805052005125005',
                'email' => 'teacher3@example.com',
                'first_name' => 'Dewi',
                'last_name' => 'Anggraini',
                'degree' => 'S.Pd',
                'address' => 'Jl. Gatot Subroto No. 7',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50241',
                'country' => 'Indonesia',
                'phone_number' => '081322334455',
                'about' => 'Guru IPA.',
                'place_of_birth' => 'Semarang',
                'date_of_birth' => '1980-05-05',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 4.png',
            ],
            [
                'nip' => '197806062006126006',
                'email' => 'teacher4@example.com',
                'first_name' => 'Ahmad',
                'last_name' => 'Fauzi',
                'degree' => 'M.Pd',
                'address' => 'Jl. Sudirman No. 10',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60241',
                'country' => 'Indonesia',
                'phone_number' => '081345678912',
                'about' => 'Guru PPKn.',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '1981-06-06',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 5.png',
            ],
            [
                'nip' => '197807072007127007',
                'email' => 'teacher5@example.com',
                'first_name' => 'Rina',
                'last_name' => 'Kartika',
                'degree' => 'S.Pd',
                'address' => 'Jl. Raya Bogor No. 55',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'postal_code' => '16112',
                'country' => 'Indonesia',
                'phone_number' => '081356789012',
                'about' => 'Guru Seni Budaya.',
                'place_of_birth' => 'Bogor',
                'date_of_birth' => '1982-07-07',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 6.png',
            ],
            [
                'nip' => '197808082008128008',
                'email' => 'teacher6@example.com',
                'first_name' => 'Hendra',
                'last_name' => 'Saputra',
                'degree' => 'S.Pd',
                'address' => 'Jl. Pemuda No. 21',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20151',
                'country' => 'Indonesia',
                'phone_number' => '081377788899',
                'about' => 'Guru Ekonomi.',
                'place_of_birth' => 'Medan',
                'date_of_birth' => '1983-08-08',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 7.png',
            ],
            [
                'nip' => '197809092009129009',
                'email' => 'teacher7@example.com',
                'first_name' => 'Indah',
                'last_name' => 'Pratiwi',
                'degree' => 'M.Pd',
                'address' => 'Jl. Adi Sucipto No. 33',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90145',
                'country' => 'Indonesia',
                'phone_number' => '081245678999',
                'about' => 'Guru Biologi.',
                'place_of_birth' => 'Makassar',
                'date_of_birth' => '1984-09-09',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 8.png',
            ],
            [
                'nip' => '197810102010130010',
                'email' => 'teacher8@example.com',
                'first_name' => 'Made',
                'last_name' => 'Wijaya',
                'degree' => 'S.Pd',
                'address' => 'Jl. Raya Kuta No. 88',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80221',
                'country' => 'Indonesia',
                'phone_number' => '081246789123',
                'about' => 'Guru Seni Tari.',
                'place_of_birth' => 'Denpasar',
                'date_of_birth' => '1985-10-10',
                'gender' => 'L',
                'religion' => 'Hindu',
                'role' => 'teacher',
                'profile' => 'profile 9.png',
            ],
            [
                'nip' => '197811112011131011',
                'email' => 'teacher9@example.com',
                'first_name' => 'Maria',
                'last_name' => 'Kristina',
                'degree' => 'S.Pd',
                'address' => 'Jl. Sam Ratulangi No. 15',
                'city' => 'Manado',
                'province' => 'Sulawesi Utara',
                'postal_code' => '95111',
                'country' => 'Indonesia',
                'phone_number' => '081234555666',
                'about' => 'Guru Bahasa Inggris.',
                'place_of_birth' => 'Manado',
                'date_of_birth' => '1986-11-11',
                'gender' => 'P',
                'religion' => 'Kristen',
                'role' => 'teacher',
                'profile' => 'profile 10.png',
            ],
            [
                'nip' => '197812122012132012',
                'email' => 'teacher10@example.com',
                'first_name' => 'Joko',
                'last_name' => 'Susilo',
                'degree' => 'M.Pd',
                'address' => 'Jl. Malioboro No. 77',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55271',
                'country' => 'Indonesia',
                'phone_number' => '081267890123',
                'about' => 'Guru Fisika.',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '1987-12-12',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 11.png',
            ],
            [
                'nip' => '197901132013133013',
                'email' => 'teacher11@example.com',
                'first_name' => 'Sri',
                'last_name' => 'Handayani',
                'degree' => 'S.Pd',
                'address' => 'Jl. Gajah Mada No. 9',
                'city' => 'Pontianak',
                'province' => 'Kalimantan Barat',
                'postal_code' => '78111',
                'country' => 'Indonesia',
                'phone_number' => '081298765432',
                'about' => 'Guru Geografi.',
                'place_of_birth' => 'Pontianak',
                'date_of_birth' => '1988-01-13',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 12.png',
            ],
            [
                'nip' => '197902142014134014',
                'email' => 'teacher12@example.com',
                'first_name' => 'Ridwan',
                'last_name' => 'Hakim',
                'degree' => 'S.Pd',
                'address' => 'Jl. Asia Afrika No. 4',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40112',
                'country' => 'Indonesia',
                'phone_number' => '081245612378',
                'about' => 'Guru Sosiologi.',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '1989-02-14',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 13.png',
            ],
            [
                'nip' => '197903152015135015',
                'email' => 'teacher13@example.com',
                'first_name' => 'Farida',
                'last_name' => 'Azzahra',
                'degree' => 'M.Pd',
                'address' => 'Jl. Ahmad Yani No. 101',
                'city' => 'Padang',
                'province' => 'Sumatera Barat',
                'postal_code' => '25115',
                'country' => 'Indonesia',
                'phone_number' => '081223334455',
                'about' => 'Guru Sejarah.',
                'place_of_birth' => 'Padang',
                'date_of_birth' => '1990-03-15',
                'gender' => 'P',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 14.png',
            ],
            [
                'nip' => '197904162016136016',
                'email' => 'teacher14@example.com',
                'first_name' => 'Yusuf',
                'last_name' => 'Maulana',
                'degree' => 'S.Pd',
                'address' => 'Jl. Imam Bonjol No. 25',
                'city' => 'Pekanbaru',
                'province' => 'Riau',
                'postal_code' => '28111',
                'country' => 'Indonesia',
                'phone_number' => '081277788899',
                'about' => 'Guru Olahraga.',
                'place_of_birth' => 'Pekanbaru',
                'date_of_birth' => '1991-04-16',
                'gender' => 'L',
                'religion' => 'Islam',
                'role' => 'teacher',
                'profile' => 'profile 15.png',
            ],
        ];

        foreach ($users as $u) {
            $destinationPath = 'profile_pictures/' . $u['profile'];

            // copy hanya jika file ada di public
            $sourcePath = public_path($u['profile']);
            if (file_exists($sourcePath)) {
                Storage::disk('public')->put($destinationPath, file_get_contents($sourcePath));
            }

            User::create([
                'nip' => $u['nip'],
                'email' => $u['email'],
                'first_name' => $u['first_name'],
                'last_name' => $u['last_name'],
                'degree' => $u['degree'],
                'address' => $u['address'],
                'city' => $u['city'],
                'province' => $u['province'],
                'postal_code' => $u['postal_code'],
                'country' => $u['country'],
                'phone_number' => $u['phone_number'],
                'about' => $u['about'],
                'place_of_birth' => $u['place_of_birth'],
                'date_of_birth' => $u['date_of_birth'],
                'gender' => $u['gender'],
                'religion' => $u['religion'],
                'role' => $u['role'],
                'profile_picture' => $destinationPath,
                'password' => bcrypt('password'),
            ]);
        }
    }
}
